id,rarity,weapon,element,description,region,birthday,constellation
albedo,5,Sword,Geo,An alchemist based in Mondstadt, in the service of the Knights of Favonius.,Mondstadt,September 13th,Princeps Cretaceus
aloy,5,Bow,Cryo,An agile hunter from the Nora tride. With bow in hand, she's always ready to protect the innocent.,Horizon Zero Dawn,April 4th,Nora Fortis
amber,4,Bow,Pyro,A perky, straightforward girl, who is also the only Outrider of the Knights of Favonius. Her amazing mastery of the glider has made her a three-time winner of the Gliding Championship in Mondstadt. As a rising star within the Knights of Favonius, Amber is always ready for any challenging tasks.,Mondstadt,August 10th,Lepus
ayaka,5,Sword,Cryo,The princess of the House Kamisato of Inazuma. She is the embodiment of nobility and elegance.,Inazuma,September 28th,Grus Nivis
barbara,4,Catalyst,Hydro,The Deaconess of the Favonius Church and a shining starlet adored by all. Although the concept of a starlet is rather novel in a city of bards, the people of Mondstadt love Barbara nonetheless. "I owe everything to the city's spirit of freedom" — Barbara, regarding her popularity.,Mondstadt,July 5th,Crater
beidou,4,Claymore,Electro,Captain of the Crux, with quite the reputation in Liyue. There are those who say she can split mountains and part the sea. Others say she draws lightning through her sword. Some say that even the mightiest of sea beasts are no match for her. For those not from Liyue, it may sound like a hearty joke, but those that have sailed with her will say- "No matter what sea beasts there may be, Beidou will be sure to split them all in two.,Liyue,February 14th,Victor Mare
bennett,4,Sword,Pyro,The few young adventurers that the Mondstadt Adventurers' Guild has always find themselves tangled up in baffling bouts of bad luck. He is the only active member of his own adventure group, known as "Benny's Adventure Team," after all the other members decided to "take leave" following a series of unfortunate incidents. As a result, the team is currently on the verge of being dissolved. Being unable to break the poor boy's heart, Katheryne of the Adventurers' Guild has kept "Benny's Adventure Team" on the books, whilst also hiding from him the fact that all the other members have long since officially left the team.,Mondstadt,February 29th,Rota Calamitas
chongyun,4,Claymore,Cryo,An exorcist who roams the land with Liyue as his base of operations, evil spirits fleeing wherever he goes. As the heir to a clan of exorcists, he has always possessed abilities superior to most. However, these abilities are not the result of training, but of an inborn trait - congenital positivity,Liyue,September 7th,Nubis Caesor
dainsleif,0,sword,NULL,Dainsleif is a man of mysterious origins, but claims to have knowledge of fate itself. Previously known as the "Twilight Sword", he was one of the royal guards of the final dynasty of Khaenri'ah.,Khaenri'ah,,
diluc,5,Claymore,Pyro,As the wealthiest gentleman in Mondstadt, the ever-dapper Diluc always presents himself as the epitome of perfection. But behind the courteous visage burns a zealous soul that has sworn to protect Mondstadt at all costs, allowing him to mercilessly vanquish all who threaten his city.,Mondstadt,April 30th,Noctua
diona,4,Bow,Cryo,A young lady who has inherited trace amounts of non-human blood. She is the incredible popular bartender of the Cat's Tail tavern.,Mondstadt,January 18th,Feles
eula,5,Claymore,Cryo,The Spindrift Knight, a scion of the old aristocracy, and the Captain of the Knights of Favonius Reconnaissance Company. The reason for which a descendant of the ancient nobles might join the Knights remains a great mystery in Mondstadt to this very day.,Mondstadt,October 25th,Aphros Delos
fischl,4,Bow,Electro,A mysterious girl who calls herself "Prinzessin der Verurteilung" and travels with a night raven named Oz. Currently serves as an investigator in the Adventurers' Guild. Through her unique abilities, eccentric character, and (while she would never admit it herself) hard work, Fischl has become a rising star among the Adventurers' Guild's investigators, earning the recognition of all.,Mondstadt,May 27th,Corvus
ganyu,5,Bow,Cryo,The secretary to the Liyue Qixing. The blood of both human and illuminated beast flows within her veins.,Liyue,December 2nd,Sinae Unicornis
gorou,4,Bow,Geo,The great general of Watatsumi Island's forces. He has gained respect and prestige, but always shows himself to be a humble leader. He is deeply trusted by his subordinates and is someone with whom you can share your feelings without shame.,Inazuma,May 18th,Canis Bellatoris
hu-tao,5,Polearm,Pyro,Hu Tao is the 77th Director of the Wangsheng Funeral Parlor, a person vital to managing Liyue's funerary affairs.,Liyue,July 15th,Papilio Charontis
itto,5,Claymore,Geo,Descendant of the oni, of intrepid spirit and noble heart. Fast as the wind and mighty as thunder.,Inazuma,June 1st,Taurus Iracundus
jean,5,Sword,Anemo,As the Acting Grandmaster of the Knights, Jean has always been devoted to her duties and maintaining peace in Mondstadt. She had taken precautions long before the onset of Stormterror's assault, and she will guard Mondstadt with her life as always.,Mondstadt,March 14th,Leo Minor
kaeya,4,Sword,Cryo,In the Knights of Favonius, Kaeya is the most trusted aide for the Acting Grand Master Jean. You can always count on him to solve any intractable problems. Everyone in Mondstadt loves Kaeya, but no one knows what secrets this witty, charming knight has..,Mondstadt,November 30th,Pavo Ocellus
kazuha,5,Sword,Anemo,A wandering samurai from Inazuma with a modest and gentle personality. Beneath a youthful and carefree demeanor lies a heart that hides a great many burdens from the past. Seemingly easygoing, Kazuha has his own code of conduct.,Inazuma,October 29,Acer Palmatum
keqing,5,Sword,Electro,The Yuheng of the Liyue Qixing. Keqing has much to say about Rex Lapis' unilateral approach to policymaking in Liyue ⁠— but in truth, gods admire skeptics such as her quite a lot.,Liyue,November 20th,Trulla Cementarii
klee,5,Catalyst,Pyro,An explosives expert and a regular at the Knights of Favonius' confinement room. Also known as Fleeing Sunlight.,Mondstadt,July 27th,Trifolium
kokomi,5,Catalyst,Hydro,Kokomi is the Divine Priestess of Watatsumi Island, and also serves as its supreme leader. She is well-versed in the art of war, is good at strategizing and has keen insights into military affairs. She is also adept at handling domestic affairs, diplomacy, and other matters. Still, this unfathomable leader has a mysterious side to her...,Inazuma,February 22nd,Dracaena Somnolenta
lisa,4,Catalyst,Electro,The librarian of the Knights of Favonius. In addition to her elegance and charm, Lisa is also highly educated. She is said to have been the most talented sorceress to study at the Sumeru Academia in the last two centuries. It is known that Lisa chose to return to Mondstadt after two years of advanced study in Sumeru, but the reason for the decision is not. Lisa currently serves as a librarian in the Knights of Favonius. She is an intellectual witch who can never get enough naps. As the Librarian of the Knights of Favonius, Lisa is smart in that she always knows exactly what to do with whatever troubles her. As much as she loves her sleep, she still manages to keep everything under control in a calm, composed manner.,Mondstadt,June 9th,Tempus Fugit
miko,5,Catalyst,Electro,The head shrine maiden in charge of Grand Narukami Shrine and a descendant of Kitsune lineage, Eternity's servant and friend, and the intimidating editor-in-chief of Yae Publishing House, a publisher of light novels...
The enigmatic Guuji, with many identities, may never be fully understood by mortals for what she truly is in her heart of hearts.,Inazuma,June 27th,Divina Vulpes
mimi,0,catalyst,hydro,,Inazuma,,
mona,5,Catalyst,Hydro,A mysterious young astrologer who proclaims herself to be "Astrologist Mona Megistus," and who possesses abilities to match the title. Erudite, but prideful.,Mondstadt,August 31st,Astrolabos
ningguang,4,Catalyst,Geo,Owner of the Jade Chamber in the skies above Liyue, there are stories abound about Ningguang, with her elegance and mysterious smile. As a Tianquan of the Liyue Qixing, not only does she embody law and order, she also represents fortune and wit.,Liyue,August 26th,Opus Aequilibrium
noelle,4,Claymore,Geo,Like most of Mondstadt's young people, Noelle always dreamed of being a knight of Favonius when she grew up. She may not have what it takes to be a knight just yet, but she is learning. Working as a maid at the Knights' headquarters, she is constantly taking notes on what constitutes knightly speech, knightly conduct, and knightly customs. She holds firm to her belief that one day she will join their ranks - she just needs to keep trying her hardest at everything she does.,Mondstadt,March 21st,Parma Cordis
paimon,0,,,Paimon is a non-playable character in Genshin Impact and accompanies the Traveler throughout their adventure in Teyvat as their guide. She met the Traveler by being fished out of a lake in which she mentions she would've drowned if not being fished out. She is currently representing Genshin Impact and is on the Genshin Impact app, website, and social media icons.,Mondstadt,June 1st,
qiqi,5,Sword,Cryo,An apprentice and herb gatherer at Bubu Pharmacy. "Blessed" by the adepti with a body that cannot die, this petite zombie cannot do anything without first giving herself orders to do it. Qiqi's memory is like a sieve. Out of necessity, she always carries around a notebook in which she writes anything important that she is sure to forget later.,Liyue,March 3rd,Pristina Nola
razor,4,Claymore,Electro,Some say he is an orphan raised by wolves. Others say he is a wolf spirit in human form. He is most at home in the wild, fighting with claw and thunder. To this day the wolf boy can be found prowling the forest, where he and his wolf pack hunt to survive using nothing more than their animal instincts.,Mondstadt,September 9th,Lupus Minor
rosaria,4,Polearm,Cryo,Rosaria, a sister in Mondstadt's Church of Favonius. A sister of the church, though you wouldn't know it if it weren't for her attire. An unusual woman with sharp, piercing words and a cold manner. Her movements are unpredictable. She often leaves without notifying anyone. She acts with some kind of purpose, but others don't seem to know exactly what she stands for...,Mondstadt,January 24th,Spinea Corona
sara,4,Bow,Electro,Leader of the Tenryou Commission's forces. A charismatic woman who acts as swiftly as a storm wind and always honors her word. She bears the title of "Devotee of the Divine" and has sworn her allegiance to the Raiden Shogun.,Inazuma,July 14th,Flabellum
sayu,4,Claymore,Anemo,A pint-sized ninja attached to the Shiyuumatsu-Ban, who always seems sleep-deprived.,Inazuma,October 19th,Nyctereutes Minor
scaramouche,5,catalyst,electro,,Snezhnaya,,
shenhe,5,Polearm,Cryo,Even though she was born in the human world, she ended up being an adepti disciple. She grew up in the mountains far away from Liyue Harbor, her soul bound with red ropes, training both her body and mind. Despite having the elegant temperament of an adeptus, she seems to be shrouded in mystery.,Liyue,March 10th,Crista Doloris
shogun,5,Polearm,Electro,The Raiden Shogun is the awesome and terrible power of thunder incarnate, the exalted ruler of the Inazuma Shogunate. With the might of lightning at her disposal, she commits herself to the solitary pursuit of eternity.,Inazuma,June 26th,Imperatrix Umbrosa
sucrose,4,Catalyst,Anemo,An alchemist with an insatiable curiosity towards the world and everything in it. Attached to the Knights of Favonius as an assistant to Albedo, her area of focus is "bio-alchemy." She strives to enrich the world by transforming living things with the power of alchemy.,Mondstadt,November 26th,Ampulla
tartaglia,5,Bow,Hydro,Meet Tartaglia — the cunning Snezhnayan whose unpredictable personality keeps people guessing his every move.,Snezhnaya,July 20th,Monoceros Caeli
thoma,4,Polearm,Pyro,Perhaps influenced by the relaxed and happy atmosphere of his hometown, Thoma is very good at socializing. Although he is an outlander, he has built an unexpectedly powerful network of people in Inazuma.,Inazuma,January 9th,Rubeum Scutum
traveler-anemo,5,Sword,Anemo,The Traveler is the protagonist and a playable character in Genshin Impact. At the beginning of the game, both genders are twin siblings from another world, travelling throughout the universe, until an Unknown God ambushed, capturing one of them, and sealed their ways to travel, leaving them stranded on Teyvat.,Mondstadt,Player's Choice,Viator/Viatrix
traveler-electro,5,Sword,Electro,The Traveler is the protagonist and a playable character in Genshin Impact. At the beginning of the game, both genders are twin siblings from another world, travelling throughout the universe, until an Unknown God ambushed, capturing one of them, and sealed their ways to travel, leaving them stranded on Teyvat.,Inazuma,Player's Choice,Viator/Viatrix
traveler-geo,5,Sword,Geo,The Traveler is the protagonist and a playable character in Genshin Impact. At the beginning of the game, both genders are twin siblings from another world, travelling throughout the universe, until an Unknown God ambushed, capturing one of them, and sealed their ways to travel, leaving them stranded on Teyvat.,Liyue,Player's Choice,Viator/Viatrix
venti,5,Bow,Anemo,A bard that seems to have arrived on some unknown wind - sometimes sings songs as old as the hills, and other times sings poems fresh and new. Likes apples and lively places, but is not a fan of cheese or anything sticky. When using his Anemo power to control the wind, it often appears as feathers, as he's fond of that which appears light and breezy.,Mondstadt,June 16th,Carmen Dei
xiangling,4,Polearm,Pyro,The Head Chef at the Wanmin Restaurant and also a waitress there, Xiangling is extremely passionate about cooking and excels at her signature hot and spicy dishes. Though still young, Xiangling is a true master of the culinary arts with all the skills of a kitchen veteran. She enjoys a good reputation among the hearty eaters at Chihu Rock. There's absolutely no need to be nervous if she wants you to sample her latest creation. It will not disappoint. Promise.,Liyue,November 2nd,Trulla
xiao,5,Polearm,Anemo,One of the "Mighty and Illuminated Adepti" guarding Liyue, also heralded as the "Guardian Yaksha". Despite his appearance as a young man, occasional legends about him have been documented in ancient books. He is especially fond of Wangshu Inn's Almond Tofu. The reason is that the dish tastes just like the "dreams" he used to devour.,Liyue,April 17th,Alatus Nemeseos
xingqiu,4,Sword,Hydro,The second son of the Feiyun Commerce Guild, Xingqiu has had a reputation for being studious and polite ever since he was a young child. But there is another side to the mild-mannered Xingqiu everyone knows. A daring, adventurous and much more mischievous side...,Liyue,October 9th,Fabulae Textile
xinyan,4,Claymore,Pyro,Rock 'n' roll is an avant-garde art in Liyue Harbor and Xinyan is the pioneer in this field. She rebels against ossified prejudices, using her music and passionate singing to awaken dazed souls fatigued by worldly matters. If you get the chance, do not miss out on her next performance!,Liyue,October 16th,Fila Ignium
yanfei,4,Catalyst,Pyro,A half-illuminated beast and highly-skilled legal adviser. She combines adherence to the legal codices and reasonable flexibility to find the perfect balance in her work. She devotes herself to protecting the fairness of contracts in Liyue with her identity as a legal adviser and her unique experience and methods.,Liyue,July 28th,
Bestia Iustitia
yaoyao,0,catalyst,Dendro,,Liyue,,
yoimiya,5,Bow,Pyro,Owner of Naganohara Fireworks, known as "Queen of the Summer Festival," she excels in her craft of creating fireworks that symbolize people's hopes and dreams.,Inazuma,June 21st,Carassius Auratus
yunjin,4,Polearm,Geo,The current director of the Yun-Han Opera Troupe, a renowned Liyue opera singer who is skilled in both playwriting and singing. Her style is one-of-a-kind, exquisite and delicate, much like the person herself.,Liyue,May 21st,Opera Grandis
zhongli,5,Polearm,Geo,Wangsheng Funeral Parlor's mysterious consultant. Handsome, elegant, and surpassingly learned. Though no one knows where Zhongli is from, he is a master of courtesy and rules. From his seat at Wangsheng Funeral Parlor, he performs all manner of rituals.,Liyue,December 31st,Lapid Dei
